name: Main

on: 
  push:
    paths-ignore:
      - notes.md

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: | 
          sudo apt-get install xorg-dev
          sudo apt-get install libxcb-shape0-dev
          sudo apt-get install libxcb-xfixes0-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test --verbose
      - name: Ignored Tests
        run: cargo test -- --ignored
      - name: Build
        run: cargo build --verbose
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test
      - name: Ignored Tests
        run: cargo test -- --ignored
      - name: Build
        run: cargo build --verbose
      